version: "3"

services:
  nostrex_postgres:
    container_name: nostrex_postgres
    image: postgres:15.1
    ports:
      - "5500:5432"
    volumes:
      - nostrex_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nostrex_dev

volumes:
  nostrex_data:


