config:
  # target: "wss://nostrex.fly.dev"
  target: "ws://localhost:4000"
  processor: "./load_test.js"
  phases:
    - duration: 20
      arrivalRate: 10
      name: Warm up
  # payload:
    # path: "messages.csv"
    # fields:
    #  - "not applicable"

scenarios:
  - name: "test scenario"
    engine: ws
    flow:
      - connect: "{{ target }}"
      - loop:
        - function: "createMessage"
        - send: "{{ message }}"
        count: 5
      - loop:
        - function: "createSubscription"
        - send: "{{ message }}"
        count: 2
      - loop:
        - function: "createMessage"
        - send: "{{ message }}"
        count: 50
      



